### ISSUE TITLE
dyn. vs. statische IP Adresse

### ISSUE THREAD

**Issue by fkoussen** [jp112sdl/CCU2GW#2]
Dickes Lob für Deine Entwicklung - könntest Du bitte im Readme noch kurz auf das Thema IP-Adresse eingehen. Ich hatte für meine CCU2 eine statische IP-Adresse und bin mir nun nicht sicher, ob es ausreicht /etc/config/netconfig entsprechend zu ändern oder ob ich die Netzwerkeinstellungen VORHER (bzw. nach "re-config") im WebGUI entsprechend auf DHCP hätte einstellen müssen.

**Comment by jp112sdl** [comment]
Hi, ich kann dir dazu leider auch keine konkreten Tipps geben. Habe mich damit nie beschäftigt. 

Ich denke aber, die WebUI macht auch nix anderes, als die `/etc/config/netconfig` zu schreiben.
Setz einfach mal `MODE=DHCP` und schau was passiert.

Evtl. sonst auch im Homematic Forum einen neuen Thread zur Diskussion stellen; vielleicht weiß dort jemand Bescheid.

**Comment by fkoussen** [comment]
Gerade ausprobiert: Die Änderung der statischen Adresse NACH der Umkonfiguration zum LANGW in /etc/config/netconfig funktioniert
