### ISSUE TITLE
Gateway stellt alle 4-8 Tage den Betrieb ein

### ISSUE THREAD

**Issue by Elluminatus** [jp112sdl/CCU2GW#3]
Hallo und guten Tag. Ich habe eine alte CCU2 in ein Gateway umgewandelt. Es klappt auch alles wunderbar. Einziges Problem ist wie oben bereits beschrieben. Das Gateway ist nach 4-8 Tagen nicht mehr erreichbar. Ping auf die IP bleibt erfolglos. Nach dem trennen von der Steckdose und somit Neustart funktioniert alles wieder tadellos.

Gibt es eine Idee oder einen Hinweis hierzu?

Danke sehr
und beste Grüße
Elluminatus

**Comment by jp112sdl** [comment]
Hi,

ich kann dir da leider nicht weiterhelfen.

Ein Hardwaredefekt ist wohl nicht auszuschließen. 
Oder es gibt ein Problem in deinem Netzwerk... doppelt vergebene IP von einem Gerät, das nicht dauerhaft an ist?

**Comment by Elluminatus** [comment]
Hi, danke für die schnelle Antwort. Eine doppelte IP gibt es nicht, sind alle einzeln fest vergeben und DHCP hat einen anderen Teilbereich. 

Anzumerken sei vllt noch, dass das Gerät seinen Dienst in einer Garage versieht. Vllt hat es auch etwas mit der Temperatur zu tun?
Ansonsten behalte ich es nochmal im Auge... Leider kann ich aber auch kein Log etc. auslesen... Die IP Cam die noch dort verbaut ist, ist zuverlässig anpingbar. Wie gesagt nach reset alles wieder wunderbar. 

Was für ein Linux liegt dem ganzen zugrunde? Gibt es irgendwo logs etc und kann ich Dinge wie z.B. kleine Hilfprogramme normal installieren?

Danke für die Hilfe!

Beste Grüße
Elluminatus

**Comment by jp112sdl** [comment]
> Vllt hat es auch etwas mit der Temperatur zu tun?

Durchaus möglich. Gepaart mit Luftfeuchtigkeit, Kondenswasserbildung etc...

> Was für ein Linux liegt dem ganzen zugrunde?

Ich glaub irgendeine uralte BusyBox Version

> Gibt es irgendwo logs 

Glaub nicht. Nur rudimentär was in `/var/log`

> kann ich Dinge wie z.B. kleine Hilfprogramme normal installieren?

Nein. Da läuft kein vollwertiges Linux mit Paketmanager etc.

**Comment by Elluminatus** [comment]
Danke für die Infos! Ich werde jetzt mal versuchen in der crontab mit crontab -e den Befehl reinzuschreiben, dass das Gateway alle 24h um 3 Uhr einen reboot macht. Mal sehen ob es dann besser klappt.

**Comment by peter9teufel** [comment]
> Danke für die Infos! Ich werde jetzt mal versuchen in der crontab mit crontab -e den Befehl reinzuschreiben, dass das Gateway alle 24h um 3 Uhr einen reboot macht. Mal sehen ob es dann besser klappt.

Hi!
Hat ein daily reboot via Cronjob eine Besserung gebracht? Bin nämlich auch gerade dabei meine alte CCU2 zum Gateway zu machen.

Beste Grüße!
