### ISSUE TITLE
wget fails with OpenSSL error (old TLS Version)

### ISSUE THREAD

**Issue by ScharffenbergFrank** [jp112sdl/CCU2GW#4]
wget on CCU2 uses tlsv1, but it seens that github does'n support version 1

Resolving raw.githubusercontent.com... 185.199.110.133, 185.199.109.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com|185.199.110.133|:443... connected.
OpenSSL: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
Unable to establish SSL connection.

Therefore the wget command fails. And because of parameter -q without error message.

Workaround: download on host and copy via scp manually ...

**Comment by jp112sdl** [comment]
Which CCU2 Firmware Version are you using?

**Comment by ScharffenbergFrank** [comment]
How can I get the CCU2 firmware version, unfortunately the CCU is just runnig as gateway without webUi :-(

uname -a
Linux homematicLANGW 3.4.11.ccu2 #1 PREEMPT Tue Jul 3 14:50:56 CEST 2018 armv5tejl GNU/Linux

--> probably version 2.35.16 (released: 2018-07-04) 

wget version is 
wget --version
GNU Wget 1.13.4 built on linux-gnueabi.

CCU2 firmware update may help... FW 2.57.x contains wget 1.20.x,  probably with tls2.x support

**Comment by ScharffenbergFrank** [comment]
Wie können auch in deutsch weitermachen - bei GitHub schalte ich immer die Sprache um :-) 
Bin gerade zur CCU-Funktion zurück gewechselt, Firmware ist 2.35.16. Ich mache ein Update auf die aktuele Version (2.59.7) und teste dann nochmal

**Comment by jp112sdl** [comment]
Ja, besten Dank. 
Ich zurzeit keine CCU2 mit der ich weitere Tests machen könnte.

**Comment by ScharffenbergFrank** [comment]
mit FW 2.59.7 geht wget

```
wget --no-check-certificate -O /firmware/fwmap https://raw.githubusercontent.com/jp112sdl/CCU2GW/master/fwmap
--2021-12-10 10:28:49--  https://raw.githubusercontent.com/jp112sdl/CCU2GW/master/fwmap
Resolving raw.githubusercontent.com... 185.199.108.133, 185.199.111.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 282 [text/plain]
Saving to: '/firmware/fwmap'

/firmware/fwmap                                         100%[========================================================================================================================================>]     282  --.-KB/s    in 0.001s

2021-12-10 10:28:50 (551 KB/s) - '/firmware/fwmap' saved [282/282]
```

Ich konnte nicht herausbekommen, ab welcher CCU-FW wget mit tls > 1.0 verfügbar ist. 

Vorschlag: 

- Ergänze Deine Anleitung um einen Hinweis zum Update CCU-FW. 
- nimm den Parameter -q aus wget raus oder prüfe mit `if [ ! -f <filename> ]`, ob der Download erfolgreich war und ergänze eine Hinweis, dass ohne Download nicht weitergemacht werden darf
- kommentiere `echo XXXXXXXXXX > /usr/local/addons/serialnumber.txt` aus, gefährlich für unbedarfte Nutzer

Und danke für Deine Anleitung!

**Comment by jp112sdl** [comment]
Danke für deine Hinweise.
