### ISSUE TITLE
CCU3 hängt sich, beim Verbinden mit dem CCU2 Gateway, auf

### ISSUE THREAD

**Issue by schmidtas** [jp112sdl/CCU2GW#5]
Guten Morgen,

auch ich möchte die CCU2 als Repeater nehmen um die HM-Füllstandsanzeige für Zisternen von ELV an meine CCU3 anbinden zu können.
Meiner Meinung nach funktioniert das flashen ohne Probleme.
Die Ausgangs-FW auf der CCU2 ist: 2.61.7

Das Neubespielen läuft meiner Meinung nach sauber durch.
Die CCU2 kann ich hinterher auch problemlos im Netzwerk anpingen.
Füge ich diese der CCU3 als LAN Gateway hinzu hängt sich diese komplett auf.
Es geht nahezu überhaupt nichts mehr und ich bekomme die Fehlermeldung: Eine Komponente der Homematic Zentrale reagiert nicht mehr.....

Trenne ich die CC2 vom Lan, funktioniert alles wieder ohne Probleme.

Ist das Problem bekannt, bzw. wie kann ich dieses Problem lösen?

**Comment by jp112sdl** [comment]
> Die Ausgangs-FW auf der CCU2 ist: 2.61.7

Waren / Sind dort vormals irgendwelche Firewallregeln eingerichtet worden?


> Füge ich diese der CCU3 als LAN Gateway hinzu hängt sich diese komplett auf.

Seriennummer und IP sind richtig angegeben, Sicherheitsschlüssel ist leer gelassen?


Welche LEDs leuchten an der CCU2 ?

**Comment by schmidtas** [comment]
Guten Abend Jérôme,

richtig die Ausgangs-FW ist die 2.6.1.7.
Im Vorfeld habe ich die CCU2 komplett auf Werkseinstellungen zurückgesetzt.
Ich gehe davon aus, dass evtl. vorhandene Firewallregeln dadurch eliminiert wurden.
Die CCU2 habe ich gebraucht gekauft, da ich selbst nur die CCU3 im Einsatz habe.
Die IP ist korrekt hinterlegt. Den Sicherheitsschlüssel habe ich leer gelassen.

Ich habe es ohne Seriennummer probiert.
Bei einigen Tutorials habe ich im Internet gelesen, dass die Seriennummer nicht zwingend hinterlegt werden muss und automatisch gezogen wird. Das ist wohl eine falsche Information. 

Auf Grund deiner expliziten Frage, habe ich es nun nochmal mit der Standard-Seriennummer versucht.
**-> Das bringt die Lösung** Die Verbindung funktioniert nun problemlos. 

Vielen Dank für deinen Support und dir alles Gute für die Zukunft!!

**Comment by jp112sdl** [comment]
Danke für die positive Rückmeldung!
