### ISSUE TITLE
Firmware Downgrade bei der CCU2 für den Lan Gateway Betrieb

### ISSUE THREAD

**Issue by fa11enangel** [jp112sdl/CCU2GW#6]
Ist es richtig, dass die Firmware des Funkmoduls von Version 2.8.6 auf Version 1.4.1 down gegradet wird?

Das war bei mir in den Protokollen:

```sh
# eq3configcmd update-coprocessor -p /dev/mxs_auart_raw.0 -c -u -d /firmware
2024/04/01 11:50:02.025 <Info> Version: 2.8.6

2024/04/01 11:50:02.029 <Info> Update necessary, installed: 2.8.6, avaiable 1.4.1

2024/04/01 11:50:09.149 <Info> Firmwareupdate successfull
```

Oder funktioniert es nur mit der alten Firmware?

**Comment by jp112sdl** [comment]
Moin!
Ja das muss so. Das ist die "BidCos-only" Firmware Version

**Comment by fa11enangel** [comment]
Danke dir!
